install! 'cocoapods', integrate_targets: false
use_frameworks!

target 'Target_for_ios' do
	platform :ios, '12.0'
	pod 'Firebase', '10.0.0'
	pod 'FBSDKCoreKit', '15.0.0'
	pod 'FBSDKLoginKit', '15.0.0'
	pod 'FBSDKShareKit', '15.0.0'
	pod 'FirebaseAnalytics', '10.0.0'
	pod 'FirebaseDatabase', '10.0.0'
	pod 'FirebaseStorage', '10.0.0'
end

target 'Target_for_osx' do
	platform :osx, '10.13'
	pod 'Firebase', '10.0.0'
	pod 'FirebaseAnalytics', '10.0.0'
	pod 'FirebaseDatabase', '10.0.0'
	pod 'FirebaseStorage', '10.0.0'
end

target 'Target_for_tvos' do
	platform :tvos, '12.0'
	pod 'Firebase', '10.0.0'
	pod 'FBSDKCoreKit', '15.0.0'
	pod 'FBSDKLoginKit', '15.0.0'
	pod 'FBSDKShareKit', '15.0.0'
	pod 'FirebaseAnalytics', '10.0.0'
	pod 'FirebaseDatabase', '10.0.0'
	pod 'FirebaseStorage', '10.0.0'
end

target 'Target_for_watchos' do
	platform :watchos, '7.0'
	pod 'FirebaseDatabase', '10.0.0'
	pod 'FirebaseStorage', '10.0.0'
end
